name: twitter_login
description: Flutter Twitter Login Plugin. Library for login with Twitter APIs OAuth service

version: 4.4.2

homepage: https://twitter.com/0maru_dev
repository: https://github.com/0maru/twitter_login

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.maru.twitter_login
        pluginClass: TwitterLoginPlugin
      ios:
        pluginClass: TwitterLoginPlugin
      macos:
        pluginClass: TwitterLoginPlugin
